#universty fee reciept generator
print("Enter student details:")
print("----------------------")
name=input("Enter student name\t:")
id=input("Enter student id\t:")
department=input("Department\t\t:")
semester=input("Semester\t\t:")
print("=====================================")
print("          CECOS UNIVERSTY")
print("              FEE SLIP")
print("=====================================")
print("Student name\t:",name)
print("Student ID\t:",id)
print("Department\t:",department)
print("Semester\t:",semester)
print("=============FEE SECTION=============")
tution_fee=input("Tution fee\t:")
library_fee=input("library fee\t:")
hostle_fee=input("hostle fee\t:")
scholarship=input("Scholarship\t:")
fine=input("Fine amount\t:")
print("=====================================")
total_fee=int(tution_fee)+int(library_fee)+int(hostle_fee)+int(fine)
print("Total Fee\t\t:",total_fee)
fee_scholarship=int(total_fee)-int(scholarship)
print("Fee after Scholarship\t:",fee_scholarship)
print("Final payable amount\t:",fee_scholarship)
print("-------------------------------------")
print("=====================================")
print("Thankyou for using fee generator")
print("=====================================")

